# Site settings
title: Smart++;
description: > # this means to ignore newlines until "baseurl:"
  Development Blog for me, Matt Crouch.
  Keeping a track of important bits and bytes that might be useful one day. 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "/blog"
twitter_username: stupler
github_username:  MattCrouch
profile_picture: "http://mattcrouch.net/images/matt_crouch.png"

paginate: 10

# Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-gist]

future: true

permalink: /:year/:month/:title/